### ISSUE TITLE
Random Provider example is broken in documentation

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [nuxt/image#52]
Once I try to use the [example](https://image.nuxtjs.org/examples/random-provider) I get an error: 
```
provider.provider.generateURL is not a function
```
repro link: https://codesandbox.io/s/nuxt-image-tlgwe?file=/providers/wonder/index.js
I also don't see the actual preview in the docs which I guess means that example is broken there too: https://take.ms/CWCGb

**Comment by farnabaz** [comment]
Thank you for the report Andrew
This happens because the module has been refactored and previews in documentation are updated to meet new behavior but project does not use the latest version.  
Will fix in the next beta release

**Comment by AndrewBogdanovTSS** [comment]
@farnabaz I'm a bit confused. Should it work with version 0.0.3 ? Or it will be fixed in the next release? I mean not the documentation, but an actual example? Or docs provide a wrong scenario?

**Comment by farnabaz** [comment]
> Should it work with version 0.0.3 ?
No. The whole repo was updated to meet the requirements of next version (0.0.4). 

The example is broken because of a breaking change.

**Comment by farnabaz** [comment]
@AndrewBogdanovTSS This should work with v0.0.4
